### ISSUE TITLE
Windows errors

### ISSUE THREAD

**Issue by babylanguagelab** [SeedlingsBabylab/idslabel#4]
Hi guys,

OK, doing the right thing here and reporting formally. Here is a screenshot of the error that my RAs get whey the are done/close-to-done the 100 blocks (note the error text that is in the command prompt I believe occurs every time, not just upon completion of blocks, may or may not be related):

![capture3](https://cloud.githubusercontent.com/assets/11390544/18438780/5e80bac4-78c8-11e6-8b0f-f982eaad5255.JPG)

**Comment by andreiamatuni** [comment]
I just went through labeling 100 blocks to try and recreate this issue. I think the problem is that certain files in the clips directory got deleted (or moved) before having the labels sent back, and this prevents the files from being released from the "Active Blocks" list for that user. So for the Jessica user in particular, it looks like they've successfully sent back 97 reliability blocks to the server, but it also looks like the server thinks Jessica is still in possession of these blocks:
- 0001_000613s_reliability:::8 
- 0274_000221_reliability:::33
- 0032_000604s_reliability:::39 

So it's expecting you to submit those back, even though you're asking it for more blocks to be able to reach 100, it thinks it's already handed out 100 blocks to you, and it's waiting for responses to the last 3 (those listed above). It's likely that these 3 blocks were downloaded and then somehow lost either through someone deleting them from the clips directory, or moving them (or the directory) somewhere else. This is why it's important to basically never touch (or move) anything in the clips directory, and to always use the same directory across sessions. If you still have that directory somewhere on the computer, with those 3 blocks still sitting in there, try using that as the clips directory and submitting blocks back that way. If not, then you're just stuck with only being able to submit 97 blocks by this user. In the latest version of the program you're able to request specific blocks from the server and this wouldn't be an issue, but the current version doesn't allow it. 

The Gateway Error response that it sends back should definitely be more informative though. I'll make sure to have this fixed before releasing the new version of the program. Thank you for bringing up this issue!
